name: deploy

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/Checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Python Syntax Check
        run: |
          python3 -V
          pip3 install Flake8
          echo "Run flake8"
          flake8 .
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/Checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip3 install -r requirements.txt
          deactivate

      - name: Package for Test
        run: |
          mkdir /tmp/django_artifacts
          cp -r . /tmp/django_artifacts
          tar czf test_artifacts.tar.gz -C /tmp/django_artifacts .
          rm -rf /tmp/django_artifacts

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-artifacts
          path: test_artifacts.tar.gz

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: test-artifacts

      - name: Extract Code
        run: |
          tar xzf test_artifacts.tar.gz

      - name: Run Tests
        run: |
          source .venv/bin/activate
          python3 manage.py test
          deactivate