name: deploy

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/Checkout@v2
      - name: Python Syntax Check
        run: |
          pip3 install Flake8
          echo "Run flake8"
          flake8 .
